## server settings
server:
  address: 127.0.0.1
  forward-headers-strategy: NATIVE
  port: 8081
  servlet:
    context-path: /
  shutdown: graceful

## import individual config
spring:
  config:
    import: optional:file:./ddauto.yml

## spring security
  security:
    user:
      name: dyndns
      password: test123

## credentials for the domainrobot sdk    
autodns:
  context: 4
  password: pwd
  url: https://api.autodns.com/v1
  user: user

## enables the validation of the configured zones
zone:
  validation:
    enabled: true
  log-file-pattern: ./ddauto-zone*

## regex-pattern to parse the entries ddauto-zone.log
  log-pattern: "(.*)\\s+-\\s+([a-zA-Z\\.-]*)\\s+(\\S*)\\s+(\\S*)"
