## server settings
server:
  address: 127.0.0.1
  forward-headers-strategy: NATIVE
  port: 8081
  servlet:
    context-path: /
  shutdown: graceful

## spring security
spring:
  security:
    user:
      name: dyndns
      password: test123

## credentials for the domainrobot sdk    
autodns:
  context: 4
  password: pwd
  url: https://api.autodns.com/v1
  user: user

## enables the validation of the configured zones
zone:
  validation:
    enabled: true
      
file:
  zone:
    log: ddauto-zone.log

ddauto:
  zones:
    -  
      name: dynhost0.info
      ns: ns0.domain.info
      hosts:
        - my0:1234567890abcdef
        - test1:1234567890abcdx
    -
      name: dynhost1.info
      ns: ns1.domain.info
      hosts:
        - my1:1234567890abcdef
        - test1:1234567890abcdx