name: Test
on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Test test
        run: mvn clean test
